# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.9.0
_src_path: gh:radio-aktywne/template-package-python
accountname: radio-aktywne
description: Storage utilities for Python 🐍
docs: true
docsurl: https://radio-aktywne.github.io/pystores
email: it@radioaktywne.pl
importname: pystores
packagename: pystores
releases: true
reponame: pystores
repourl: https://github.com/radio-aktywne/pystores
